# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_company_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='number_of_employee',
        ),
    ]
